### ISSUE TITLE
RSS feed does not validate

### ISSUE THREAD

**Issue by emmceemoore** [edavis/hnrss#11]
I've been using your feed via Slack for the last few months and it was working great until recently. Lately, new articles show up only occasionally and there are many articles which show up in the RSS feed but which don't make it into Slack.

I reached out to Slack Support to see what was up. They're not sure as to the exact reason for the issues I'm seeing but they did point out that [the feed does not validate](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fhnrss.org%2Fnewest%3Fpoints%3D50).

I'm not sure if making the feed valid will fix my issues but I thought it was worth mentioning nonetheless.

Thanks for providing this service. 😄

**Comment by edavis** [comment]
Hmm, weird. Do you have a rough idea of when things started getting wonky?

FWIW, there hasn't been any changes recently on the `author` or `atom:link` elements. If it worked before, shouldn't be a problem now.

**Comment by emmceemoore** [comment]
I originally reached out to Slack Support on 10/25. IIRC, the issue started happening a few days before that.

I agree that it should be working and I believe this is a Slack issue. The feed is not valid but the validation errors do seem silly to me.

Anywho, feel free to close this issue if you're not interested in making the feed validate.

Thanks for the response!

**Comment by edavis** [comment]
Gotcha, thanks. I was mostly curious as the last major change I made to the code had to do with adding caching-related HTTP headers but that was back in mid-September. Thought maybe those headers were messing with something on Slack's side, but that looks doubtful.

I'm going to add `http://hnrss.org/newest?points=50` to my own Slack channel and see if I notice anything strange. I'll also leave this issue open for now as Slack is one of the most popular user-agents I see in the logs and in case anybody else is experiencing the same issue they can chime in.

One stray thought I just had: Sometimes with URLs that have point or comment count filters, a "new" item won't always appear at the top of the feed. You can sometimes see it more clearly in a traditional "mailbox-style" feed reader, but once an article clears that 50 point threshold (or whatever) it shows up as unread but buried below X newer items because those X newer items got to 50 points quicker.

If Slack's feed fetcher is built with the (reasonable) expectation that new items appear in strict chronological order, that could be throwing it for a loop. Maybe they rolled out an update to their feed fetcher around late October telling it to ignore anything older than the last seen item. As long as items got to 50 points in the order they were posted, it would work. But "slow to 50" items could be missed.

**Comment by edavis** [comment]
Quick update: There's definitely something to this. I've been subscribed to `?points=50` within my Slack for about a week now and only once received any updates from the feed in that time.

Still not sure what's happening or why, though.

**Comment by emmceemoore** [comment]
Good to hear that I'm not the only one. 😉  For the HN feed, we've started using the RSS Fox plugin for Slack and we haven't missed any updates. Hopefully Slack can figure things out and get their RSS plugin working as it was before.

**Comment by emmceemoore** [comment]
The RSS Fox plugin seems to have stopped working for us now as well. I reached out to Slack support again and I got the same "[feed doesn't validate response](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fhnrss.org%2Fnewest%3Fpoints%3D50)".

I am curious why the `<author>` element is populated in your RSS feed when it's not present in the [Hacker News feed](https://news.ycombinator.com/rss).

**Comment by edavis** [comment]
Thanks, @emmceemoore.

Just a heads up that I enabled HTTPS for all feeds about a week ago (#10). All HTTP URLs should redirect properly, but try using a HTTPS URL directly if you haven't already made the change.

I think I'm going to work on the code to make it pass that validator.w3.org check. Who knows, that'll be enough.

**Comment by edavis** [comment]
Hey @emmceemoore — I've updated the RSS feed to pass the validation test: https://validator.w3.org/feed/check.cgi?url=https%3A//hnrss.org/newest%3Fpoints%3D50

Hopefully this at least gets Slack to take a closer look.

**Comment by emmceemoore** [comment]
I've re-added the `hnrss` URL to Slack and it seems to be working fine now (new articles come through on a semi-regular basis). Thanks! 🎉

**Comment by edavis** [comment]
@emmceemoore Very cool! Yeah, looks good on my end now, too.

Interestingly, I don't actually think fixing the validation errors was what ultimately did the trick. But I'm not positive about that, either.

Right after I pushed the validation fixes up, I started mucking around with my Varnish settings and, on a whim, I started dropping the `If-Modified-Since` HTTP header if the User-Agent contains "Slackbot." The theory was maybe Slack was improperly getting a HTTP 304 response and treating it as an empty feed. Seems like within a few minutes of doing that, I was getting updates within my personal Slack channel.

But who knows, maybe fixing the feed errors really _was_ the key and the Varnish changes don't actually matter one way or the other.

So, I basically broke the rules of "Developing 101" by doing two things at the same time and now I'm not sure what made it work exactly. Oh well. Maybe if I get some free-time one of these weekends I'll poke around a bit.

Feel free to re-open if the feed stops updating again in Slack. Thanks for all your help on this.
